services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_data:/var/www/html/data
      - ../.env:/var/www/html/.env:ro
    environment:
      - TZ=Asia/Novosibirsk

volumes:
  app_data:
